### ISSUE TITLE
[Feat] Plan Start View 틀 :)

### ISSUE THREAD

**Issue by vanism2091** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#23]
### 📝 작업할 내용 요약

<img width="536" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-GearCo/assets/107124308/5dd87be8-3f34-4701-b172-983399d04d56">
이부분을 하겟음니다
---

### 🛠️ Tasks

* [ ] 처음
* [ ] 모달

**Comment by earlysummer0303** [comment]
눼엥
