### ISSUE TITLE
[Feat] PlanDetailView Hifi 작업

### ISSUE THREAD

**Issue by vanism2091** [DeveloperAcademy-POSTECH/MacC-Team15-GearCo#37]
### 📝 작업할 내용 요약

PlanDetailView Hifi 작업을 합니다
---

### 🛠️ Tasks

* [ ] PlanDetailView Hifi 작업
* [ ] drag 가능하게

### 참고 이미지
<img width="490" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-GearCo/assets/107124308/b1c0d845-8be5-4a1a-9db2-96d3a6a78bb8">

**Comment by earlysummer0303** [comment]
47! 34!
